"""Construction tests for history family H1 (issue #41).

The protocol says *run construction tests first*. This is that tier, and it is
the cheap place to find out a corpus is malformed: every check here is decidable
from the generated bytes, needs no model, and would cost far more to discover at
10M tokens.

Two of these tests matter much more than the rest.

``test_the_reveal_generator_never_read_the_history`` is the structural proof
that the write side cannot see the future query. It copies the generator and its
spec into a tree containing no history at all and asserts byte-identical output.
Output unchanged by removing an input did not depend on that input. Everything
else in the corpus rests on that separation holding, and this project has twice
shipped a leakage control that looked adequate until someone examined it.

``test_every_gold_answer_is_actually_present_in_its_gold_event`` is what stops
the corpus asking unanswerable questions. A probe whose answer is not in the
history measures nothing except whether an arm hallucinates confidently, and it
would depress every arm equally while looking like a hard benchmark.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from build_delayed_reveal import build as build_reveal  # noqa: E402
from build_history_family import build as build_history  # noqa: E402
from corpus.history_family_spec import (  # noqa: E402
    DEFAULT_INSTANCES,
    DEFAULT_SEED,
    FAMILIES,
    PROPERTIES,
)

PREFIX = ROOT / "data" / "lab" / "corpus-h1" / "prefix-v0"
REVEAL = ROOT / "data" / "lab" / "corpus-h1" / "reveal-v0"


def load(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


@pytest.fixture(scope="module")
def corpus() -> dict:
    if not (PREFIX / "history.jsonl").is_file():
        pytest.skip("corpus not generated; run scripts/build_history_family.py")
    return {
        "history": load(PREFIX / "history.jsonl"),
        "labels": load(PREFIX / "construction-labels.jsonl"),
        "queries": load(REVEAL / "queries.jsonl"),
        "gold": load(REVEAL / "gold.jsonl"),
    }


# --------------------------------------------------------------- the eleven properties


def test_every_required_property_is_present_and_counted(corpus: dict) -> None:
    """Present is not enough. A property with one instance measures nothing."""
    counts: dict[str, int] = {}
    for label in corpus["labels"]:
        for name in label["properties"]:
            counts[name] = counts.get(name, 0) + 1

    missing = [p for p in PROPERTIES if p not in counts]
    assert not missing, f"properties never instantiated: {missing}"

    # Noise properties are bulk by design; the rest should reach one per instance.
    thin = {
        name: counts[name]
        for name in PROPERTIES
        if name not in {"repeated-noise", "one-off-noise", "common-fact"}
        and counts[name] < DEFAULT_INSTANCES
    }
    assert not thin, f"too few instances to measure anything: {thin}"


def test_the_history_does_not_leak_the_construction_labels(corpus: dict) -> None:
    """An arm that could read `properties` would score without doing the work."""
    for event in corpus["history"]:
        assert "properties" not in event
    text = (PREFIX / "history.jsonl").read_text(encoding="utf-8")
    for name in PROPERTIES:
        assert name not in text, f"property name {name!r} leaked into the history"


# --------------------------------------------------------------- the probes are sound


def test_every_gold_event_exists_in_the_history(corpus: dict) -> None:
    known = {event["event_id"] for event in corpus["history"]}
    dangling = [g["query_id"] for g in corpus["gold"] if g["gold_event_id"] not in known]
    assert not dangling, f"gold names events that were never written: {dangling[:5]}"


def test_every_forbidden_event_exists_in_the_history(corpus: dict) -> None:
    known = {event["event_id"] for event in corpus["history"]}
    dangling = [
        g["query_id"]
        for g in corpus["gold"]
        if g["forbidden_event_id"] and g["forbidden_event_id"] not in known
    ]
    assert not dangling, f"forbidden names events that were never written: {dangling[:5]}"


def test_every_gold_answer_is_actually_present_in_its_gold_event(corpus: dict) -> None:
    """A probe whose answer is not in the history measures only hallucination."""
    by_id = {event["event_id"]: event["text"] for event in corpus["history"]}
    unanswerable = []
    for gold in corpus["gold"]:
        text = by_id.get(gold["gold_event_id"], "")
        for fragment in gold["answer_contains"]:
            # A fragment may name alternatives with "|"; at least one must appear.
            if not any(form.strip() in text for form in fragment.split("|")):
                unanswerable.append((gold["query_id"], fragment))
    assert not unanswerable, f"answer fragments absent from their gold event: {unanswerable[:5]}"


def test_a_probe_never_asks_before_the_event_it_probes(corpus: dict) -> None:
    """Asking on day 4 about something recorded on day 11 is a leak, not a probe."""
    day_of = {event["event_id"]: event["day"] for event in corpus["history"]}
    asked = {query["query_id"]: query["asked_on_day"] for query in corpus["queries"]}
    backwards = [
        g["query_id"]
        for g in corpus["gold"]
        if asked[g["query_id"]] < day_of[g["gold_event_id"]]
    ]
    assert not backwards, f"probes asked before their evidence existed: {backwards[:5]}"


def test_the_delay_is_real_for_the_delayed_importance_family(corpus: dict) -> None:
    """The point of that family is distance. A one-day gap would not test it."""
    day_of = {event["event_id"]: event["day"] for event in corpus["history"]}
    asked = {query["query_id"]: query["asked_on_day"] for query in corpus["queries"]}
    gaps = [
        asked[g["query_id"]] - day_of[g["gold_event_id"]]
        for g in corpus["gold"]
        if g["case_id"].startswith("DELAYED")
    ]
    assert gaps, "the delayed-importance family produced no probes"
    assert min(gaps) >= 14, f"shortest delay was only {min(gaps)} days"


def test_the_queries_an_arm_sees_carry_no_gold_and_no_family(corpus: dict) -> None:
    """The family name states the failure mode; handing it over is a hint."""
    for query in corpus["queries"]:
        assert set(query) == {"query_id", "asked_on_day", "question"}


def test_gold_is_not_systematically_longer_than_its_forbidden_event(corpus: dict) -> None:
    """Length must not stand in for correctness.

    ``PMLAB-H1-BASE-E1`` found the gold longer than the forbidden event in 12 of
    12 instances of both OBSOLETE and RARE-EXC. With an OR-of-terms BM25 arm that
    is a free signal: prefer long events and score well without reading them. The
    corpus would have measured document length wearing the costume of a memory
    benchmark.

    A perfect 12/12 or 0/12 split in either direction is the failure. Some
    variation is expected and fine.
    """
    length = {event["event_id"]: len(event["text"].split()) for event in corpus["history"]}
    by_family: dict[str, list[bool]] = {}
    for gold in corpus["gold"]:
        if not gold["forbidden_event_id"]:
            continue
        family = gold["case_id"].rsplit("-", 1)[0]
        by_family.setdefault(family, []).append(
            length[gold["gold_event_id"]] > length[gold["forbidden_event_id"]]
        )

    assert by_family, "no family carries a forbidden event"
    confounded = {
        family: f"{sum(flags)}/{len(flags)} gold longer"
        for family, flags in by_family.items()
        if len(flags) > 2 and (all(flags) or not any(flags))
    }
    assert not confounded, f"length predicts the gold perfectly: {confounded}"


def test_every_probe_identifies_its_own_case(corpus: dict) -> None:
    """A question shared by two instances has two contradictory correct answers.

    PMLAB-H1-READ-E1 found this on its first ten paid probes. Three families
    varied nothing in their question text, so twelve instances asked one
    question with twelve different gold answers, and the reader correctly
    reported the notes as conflicting. Four more families collided partially,
    because the identifying noun was drawn from an eight-word list across twelve
    instances.

    The subject is now indexed by instance rather than drawn from the stream.
    This test fails if instances ever exceed the list of subjects.
    """
    questions = [query["question"] for query in corpus["queries"]]
    duplicates = {q for q in questions if questions.count(q) > 1}
    assert not duplicates, (
        f"{len(duplicates)} question(s) shared by more than one case: "
        f"{sorted(duplicates)[:3]}"
    )


def test_forbidden_events_exist_for_the_families_that_need_them(corpus: dict) -> None:
    """Recall alone cannot see the failure these families are built around."""
    needing = {"OBSOLETE", "RARE-EXC", "POISON"}
    for gold in corpus["gold"]:
        family = gold["case_id"].rsplit("-", 1)[0]
        if family in needing:
            assert gold["forbidden_event_id"], f"{gold['query_id']} has no forbidden event"


# --------------------------------------------------------------- determinism


def test_the_same_seed_reproduces_the_same_corpus() -> None:
    first, _ = build_history(DEFAULT_SEED, 3, 20)
    second, _ = build_history(DEFAULT_SEED, 3, 20)
    assert first == second


def test_a_different_seed_produces_a_different_corpus() -> None:
    first, _ = build_history(DEFAULT_SEED, 3, 20)
    other, _ = build_history(DEFAULT_SEED + 1, 3, 20)
    assert first != other


def test_adding_instances_does_not_renumber_the_existing_ones() -> None:
    """A frozen corpus must survive the family being extended later."""
    small, _ = build_history(DEFAULT_SEED, 2, 0)
    large, _ = build_history(DEFAULT_SEED, 5, 0)
    kept = {e["event_id"]: e["text"] for e in large}
    for event in small:
        assert kept.get(event["event_id"]) == event["text"], event["event_id"]


def test_every_family_is_instantiated() -> None:
    cases = {c["case_id"].rsplit("-", 1)[0] for c in build_reveal(DEFAULT_SEED, 2)[1]}
    assert cases == {name for name, _ in FAMILIES}


# --------------------------------------------------------------- the structural proof


def _island(tmp_path: Path, name: str, generator: str, planted: dict[str, Path]) -> Path:
    """A tree holding the generator, its spec, and only the files named."""
    island = tmp_path / name
    (island / "scripts" / "corpus").mkdir(parents=True)
    shutil.copy2(ROOT / "scripts" / generator, island / "scripts")
    for module in ("__init__.py", "history_family_spec.py"):
        shutil.copy2(ROOT / "scripts" / "corpus" / module, island / "scripts" / "corpus")
    for relative, source in planted.items():
        destination = island / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return island


def _run(island: Path, generator: str) -> Path:
    out = island / "out"
    result = subprocess.run(
        [sys.executable, str(island / "scripts" / generator), "--out", str(out)],
        capture_output=True, text=True, cwd=island,
    )
    assert result.returncode == 0, result.stderr
    return out


CORPUS_ROOT = "data/lab/corpus-h1"


def test_the_reveal_generator_never_read_the_history(tmp_path: Path) -> None:
    """Generate the reveal twice — with the history present, and without.

    This is the mechanical proof behind the protocol's requirement that no
    write-side component sees the future query.

    An earlier version of this test compared a history-free run against the
    frozen output and passed while the generator was deliberately mutated to
    read the history. It could not fail: with the history absent, the leaking
    branch never executed. The comparison has to be **between the two runs**,
    because that is the only pair that differs when a dependency exists.
    """
    with_history = _run(
        _island(tmp_path, "with", "build_delayed_reveal.py",
                {f"{CORPUS_ROOT}/prefix-v0/history.jsonl": PREFIX / "history.jsonl",
                 f"{CORPUS_ROOT}/prefix-v0/construction-labels.jsonl":
                     PREFIX / "construction-labels.jsonl"}),
        "build_delayed_reveal.py")
    without_history = _run(
        _island(tmp_path, "without", "build_delayed_reveal.py", {}),
        "build_delayed_reveal.py")

    for name in ("queries.jsonl", "gold.jsonl"):
        present = (with_history / name).read_bytes()
        absent = (without_history / name).read_bytes()
        assert present == absent, (
            f"{name} changes depending on whether the history is present. The reveal "
            "generator reads the prefix, which breaks the separation the protocol "
            "requires and silently flatters every arm."
        )
        assert present == (REVEAL / name).read_bytes(), f"{name} no longer matches the frozen corpus"


def test_the_history_generator_never_read_the_reveal(tmp_path: Path) -> None:
    """The same argument in the other direction, and for the same reason."""
    with_reveal = _run(
        _island(tmp_path, "with-reveal", "build_history_family.py",
                {f"{CORPUS_ROOT}/reveal-v0/queries.jsonl": REVEAL / "queries.jsonl",
                 f"{CORPUS_ROOT}/reveal-v0/gold.jsonl": REVEAL / "gold.jsonl"}),
        "build_history_family.py")
    without_reveal = _run(
        _island(tmp_path, "without-reveal", "build_history_family.py", {}),
        "build_history_family.py")

    for name in ("history.jsonl", "construction-labels.jsonl"):
        present = (with_reveal / name).read_bytes()
        absent = (without_reveal / name).read_bytes()
        assert present == absent, (
            f"{name} changes depending on whether the reveal is present. The history "
            "generator reads the gold, which is future-information leakage into the "
            "write side."
        )
        assert present == (PREFIX / name).read_bytes(), f"{name} no longer matches the frozen corpus"


def test_the_frozen_digests_match_the_frozen_files(corpus: dict) -> None:
    """A manifest that does not describe its own files is worse than none."""
    import hashlib

    for directory, pairs in (
        (PREFIX, {"history_sha256": "history.jsonl",
                  "construction_labels_sha256": "construction-labels.jsonl"}),
        (REVEAL, {"queries_sha256": "queries.jsonl", "gold_sha256": "gold.jsonl"}),
    ):
        manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
        for field, filename in pairs.items():
            digest = hashlib.sha256((directory / filename).read_bytes()).hexdigest()
            assert manifest[field] == digest, f"{directory.name}/{filename} does not match {field}"
